// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
namespace Cat_Paw_Footprint.Models;

public partial class Coupons
{
    public int CouponID { get; set; }

    public string? CouponCode { get; set; }

    public string? CouponDesc { get; set; }

    public int DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool IsActive { get; set; }

    public string? DiscountCode { get; set; }

    public string CouponName { get; set; } = null!;

    public string? TargetType { get; set; }

    public DateTime CreatedAt { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string? UpdatedBy { get; set; }

    public virtual ICollection<CouponPics> CouponPics { get; set; } = new List<CouponPics>();
}