// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Cat_Paw_Footprint.Models;

public partial class webtravelContext : DbContext
{
    public webtravelContext(DbContextOptions<webtravelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CouponPics> CouponPics { get; set; }

    public virtual DbSet<Coupons> Coupons { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CouponPics>(entity =>
        {
            entity.HasKey(e => e.CouponPicID).HasName("PK__CouponPi__440C2C0C77E5BC51");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CouponPics)
                .HasForeignKey(d => d.CouponID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponPic__Coupo__662B2B3B");
        });

        modelBuilder.Entity<Coupons>(entity =>
        {
            entity.HasKey(e => e.CouponID).HasName("PK__Coupons__384AF1DAE05F843F");

            entity.HasIndex(e => e.CouponCode, "UQ__Coupons__D349080054BB6769").IsUnique();

            entity.Property(e => e.CouponCode).HasMaxLength(50);
            entity.Property(e => e.CouponName)
                .HasMaxLength(100)
                .HasDefaultValue("");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.DiscountCode).HasMaxLength(50);
            entity.Property(e => e.DiscountValue).HasColumnType("numeric(7, 2)");
            entity.Property(e => e.TargetType).HasMaxLength(50);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}